---
- name: Ansible Tower backup stored in an S3 bucket
  hosts: "{{ my_devices }}"
  gather_facts: yes
  vars:
    user: "{{ my_user }}"
    version: "{{ my_version }}"
    my_bucket: nleiva-tower
    my_python_libraries: [ "boto", "boto3", "botocore", "selinux"]
    my_venv: /opt/my-envs/networking
    mtime: ""
    # Pass this as an extra var? but we want this for the remote host and not local host.
    # ansible_python_interpreter=/opt/my-envs/networking/bin/python

  tasks:
    - name: Ensure Python dependencies are installed
      pip:
        name: "{{ my_python_libraries }}"
        # extra_args:   "--user"
        virtualenv: "{{ my_venv }}"
      become: true

    - name: Check if backup already exists
      stat:
        path: "/home/{{ user }}/ansible-tower-setup-{{ version }}/tower-backup-latest.tar.gz"
      register: backup

    - name: Save backup modified time
      set_fact:
        mtime: "{{ '%Y-%m-%d' | strftime(backup.stat.mtime) }}"
      when: backup.stat.exists

    - name: Perform backup (if not already created today)
      become: yes
      command: "./setup.sh -b"
      args:
        chdir: "/home/{{ user }}/ansible-tower-setup-{{ version }}"
      when: mtime != ansible_date_time.date

    - name: Copy backup file to /tmp
      copy:
        src: "/home/{{ user }}/ansible-tower-setup-{{ version }}/tower-backup-latest.tar.gz"
        dest: "/tmp/tower-backup-latest.tar.gz"
        remote_src: yes
        mode: u=rw,g=r,o=r

    - name: Change file ownership and group for the Ansible backup file copy
      become: yes
      file:
        path: "/tmp/tower-backup-latest.tar.gz"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: u=rw,g=r,o=r

    - name: Upload backup to S3
      aws_s3:
        bucket: "{{ my_bucket }}"
        src: "/tmp/tower-backup-latest.tar.gz"
        object: "/backups/tower-backup-{{ ansible_date_time.date }}.tar.gz"
        mode: put
        metadata: 'Content-Type=application/x-gzip'
      when: backup.stat.exists
      # IMPORTANT: delegate to localhost to use AWS credentials
      # IMPORTANT: awx user should be able to execute /home/"{{ user }}"
      delegate_to: localhost

