---
- name: Ansible Tower backup stored in an S3 bucket
  hosts: "{{ my_devices }}"
  gather_facts: yes
  vars:
    user: "{{ my_user }}"
    version: "{{ my_version }}"
    my_bucket: nleiva-tower
    my_python_libraries: [ "boto", "boto3", "botocore", "selinux"]
    my_venv: /opt/my-envs/networking
    mtime: ""
    # Pass this as an extra var? but we want this for the remote host and not local host.
    # ansible_python_interpreter=/opt/my-envs/networking/bin/python
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

  tasks:
    - name: Ensure Python dependencies are installed
      ansible.builtin.pip:
        name: "{{ my_python_libraries }}"
        # extra_args:   "--user"
        # virtualenv: "{{ my_venv }}"
      become: true

    - name: Check if backup already exists
      ansible.builtin.stat:
        path: "/home/{{ user }}/ansible-tower-setup-{{ version }}/tower-backup-latest.tar.gz"
      register: backup

    - name: Save backup modified time
      ansible.builtin.set_fact:
        mtime: "{{ '%Y-%m-%d' | strftime(backup.stat.mtime) }}"
      when: backup.stat.exists

    - name: Perform backup (if not already created today)
      ansible.builtin.command: "./setup.sh -b"
      args:
        chdir: "/home/{{ user }}/ansible-tower-setup-{{ version }}"
      become: yes
      when: mtime != ansible_date_time.date

    - name: Copy backup file to /tmp
      ansible.builtin.copy:
        src: "/home/{{ user }}/ansible-tower-setup-{{ version }}/tower-backup-latest.tar.gz"
        dest: "/tmp/tower-backup-latest.tar.gz"
        remote_src: yes
        mode: u=rw,g=r,o=r
      become: yes

    # - name: Change file ownership and group for the Ansible backup file copy
    #   become: yes
    #   ansible.builtin.file:
    #     path: "/tmp/tower-backup-latest.tar.gz"
    #     owner: "{{ user }}"
    #     group: "{{ user }}"
    #     mode: u=rw,g=r,o=r

    - name: Upload backup to S3
      amazon.aws.aws_s3:
        bucket: "{{ my_bucket }}"
        src: "/tmp/tower-backup-latest.tar.gz"
        object: "/backups/tower-backup-{{ ansible_date_time.date }}.tar.gz"
        mode: put
        metadata: 'Content-Type=application/x-gzip'
      # TODO: this check might not be required
      # when: backup.stat.exists
      # IMPORTANT: delegate to localhost to use AWS credentials
      # IMPORTANT: awx user should be able to execute the source folder"
      # delegate_to: localhost

