---
- name: Ansible Automation Platform backup stored in an S3 bucket
  hosts: "{{ my_devices }}"
  gather_facts: true
  vars:
    user: "{{ my_user }}"
    version: "{{ my_version }}"
    ec2_region: "{{ aws_region | default('us-east-1') }}"
    my_bucket: nleiva-ansible-controller-home
    my_folder: "ansible-automation-platform-setup-bundle-{{ version }}"
    my_python_libraries: ["boto3", "botocore", "selinux"]
    mtime: ""
    check: true
  # Pass AWS credentials to remote host (is this secure?). The alternative is to run this on localhost.
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

  tasks:
    - name: Ensure Python dependencies are installed
      ansible.builtin.pip:
        name: "{{ my_python_libraries }}"
      become: true
      when: check

    - name: Check if backup already exists
      ansible.builtin.stat:
        path: "/home/{{ user }}/{{ my_folder }}/automation-platform-backup-latest.tar.gz"
      register: backup

    - name: Save backup modified time
      ansible.builtin.set_fact:
        mtime: "{{ '%Y-%m-%d' | strftime(backup.stat.mtime) }}"
      when: backup.stat.exists

    - name: Perform backup (if not already created today)
      ansible.builtin.command: "./setup.sh -b"
      args:
        chdir: "/home/{{ user }}/{{ my_folder }}"
      become: true
      when: mtime != ansible_date_time.date

    - name: Copy backup file to /tmp
      ansible.builtin.copy:
        src: "/home/{{ user }}/{{ my_folder }}/automation-platform-backup-latest.tar.gz"
        dest: "/tmp/automation-platform-backup-latest.tar.gz"
        remote_src: true
        mode: u=rw,g=r,o=r
      become: true

    - name: Make sure S3 bucket for persistent storage of Backup exists
      amazon.aws.s3_bucket:
        name: "{{ my_bucket }}"
        state: present
        region: "{{ ec2_region }}"

    - name: Upload backup to S3
      amazon.aws.aws_s3:
        bucket: "{{ my_bucket }}"
        src: "/tmp/automation-platform-backup-latest.tar.gz"
        object: "/backups/automation-platform-backup-{{ ansible_date_time.date }}.tar.gz"
        mode: put
        metadata: 'Content-Type=application/x-gzip'
